- name: Deploy staging
  hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        var: vars

    - name: Container present
      community.docker.docker_container:
        name: mycontainer
        state: present
        image: ubuntu:14.04
        command: sleep infinity