name: CI

on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: List dir
        run: ls -la

      # Runs a set of commands using the runners shell
      - name: Current dir
        run: pwd

      # Runs a set of commands using the runners shell
      - name: environs
        run: env

      - name: secrets
        env:
          ENV_DATA: ${{ secrets.ENV_FILE }}
        run: |
          echo "${ENV_DATA}"
          echo "${ENV_DATA}" > .env
          cat .env
